spring:
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 60
    jedis:
      pool:
        max-idle: 300
        max-active: 600
        max-wait: 1000
    database: 3
  datasource:
    url: jdbc:mysql://localhost:3306/aim
    username: root
    password: lovelja019127
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    spring.jpa.hibernate.naming.physical-strategy= org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
